[package]
name = "offchain"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.114"
soroban-sdk = { version = "22.0.7", features = ["testutils", "alloc"] }
soroban-fixed-point-math = "1.3.0"
governance = { path = "../contracts/governance" }
neurons = { path = "../neurons"}